<?php
/**
 * SupplierApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Thai-IDC
 *
 * What's new<br> 1.Delete book shelf change method DELETE to POST
 *
 * OpenAPI spec version: v1.1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SupplierApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SupplierApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation favoriteSupplier
     *
     * favorite supplier for web
     *
     * @param  string $platform platform (required)
     * @param  string $x_access_token access token after user login (required)
     * @param  string $x_user username or email for check log (required)
     * @param  string $action Action $push is favorite and $pull is unfavorite (required)
     * @param  string $supplier_id supplierId is id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\SuccessResponse
     */
    public function favoriteSupplier($platform, $x_access_token, $x_user, $action, $supplier_id, $lang = 'th')
    {
        list($response) = $this->favoriteSupplierWithHttpInfo($platform, $x_access_token, $x_user, $action, $supplier_id, $lang);
        return $response;
    }

    /**
     * Operation favoriteSupplierWithHttpInfo
     *
     * favorite supplier for web
     *
     * @param  string $platform platform (required)
     * @param  string $x_access_token access token after user login (required)
     * @param  string $x_user username or email for check log (required)
     * @param  string $action Action $push is favorite and $pull is unfavorite (required)
     * @param  string $supplier_id supplierId is id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\SuccessResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function favoriteSupplierWithHttpInfo($platform, $x_access_token, $x_user, $action, $supplier_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\SuccessResponse';
        $request = $this->favoriteSupplierRequest($platform, $x_access_token, $x_user, $action, $supplier_id, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\NotAuthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SystemError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation favoriteSupplierAsync
     *
     * favorite supplier for web
     *
     * @param  string $platform platform (required)
     * @param  string $x_access_token access token after user login (required)
     * @param  string $x_user username or email for check log (required)
     * @param  string $action Action $push is favorite and $pull is unfavorite (required)
     * @param  string $supplier_id supplierId is id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function favoriteSupplierAsync($platform, $x_access_token, $x_user, $action, $supplier_id, $lang = 'th')
    {
        return $this->favoriteSupplierAsyncWithHttpInfo($platform, $x_access_token, $x_user, $action, $supplier_id, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation favoriteSupplierAsyncWithHttpInfo
     *
     * favorite supplier for web
     *
     * @param  string $platform platform (required)
     * @param  string $x_access_token access token after user login (required)
     * @param  string $x_user username or email for check log (required)
     * @param  string $action Action $push is favorite and $pull is unfavorite (required)
     * @param  string $supplier_id supplierId is id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function favoriteSupplierAsyncWithHttpInfo($platform, $x_access_token, $x_user, $action, $supplier_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\SuccessResponse';
        $request = $this->favoriteSupplierRequest($platform, $x_access_token, $x_user, $action, $supplier_id, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'favoriteSupplier'
     *
     * @param  string $platform platform (required)
     * @param  string $x_access_token access token after user login (required)
     * @param  string $x_user username or email for check log (required)
     * @param  string $action Action $push is favorite and $pull is unfavorite (required)
     * @param  string $supplier_id supplierId is id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function favoriteSupplierRequest($platform, $x_access_token, $x_user, $action, $supplier_id, $lang = 'th')
    {
        // verify the required parameter 'platform' is set
        if ($platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $platform when calling favoriteSupplier'
            );
        }
        // verify the required parameter 'x_access_token' is set
        if ($x_access_token === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_access_token when calling favoriteSupplier'
            );
        }
        // verify the required parameter 'x_user' is set
        if ($x_user === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_user when calling favoriteSupplier'
            );
        }
        // verify the required parameter 'action' is set
        if ($action === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $action when calling favoriteSupplier'
            );
        }
        // verify the required parameter 'supplier_id' is set
        if ($supplier_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $supplier_id when calling favoriteSupplier'
            );
        }

        $resourcePath = '/suppliers/favorite';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($platform !== null) {
            $headerParams['platform'] = ObjectSerializer::toHeaderValue($platform);
        }
        // header params
        if ($x_access_token !== null) {
            $headerParams['x-access-token'] = ObjectSerializer::toHeaderValue($x_access_token);
        }
        // header params
        if ($x_user !== null) {
            $headerParams['x-user'] = ObjectSerializer::toHeaderValue($x_user);
        }
        // header params
        if ($lang !== null) {
            $headerParams['lang'] = ObjectSerializer::toHeaderValue($lang);
        }


        // form params
        if ($action !== null) {
            $formParams['action'] = ObjectSerializer::toFormValue($action);
        }
        // form params
        if ($supplier_id !== null) {
            $formParams['supplierId'] = ObjectSerializer::toFormValue($supplier_id);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSupplierByCategory
     *
     * Get Supplier by Category
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     * @param  string $pagination Pagination for load more supplier list. Send supplierId (_id) last array (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ProductResponse
     */
    public function getSupplierByCategory($platform, $category_id, $lang = 'th', $pagination = null)
    {
        list($response) = $this->getSupplierByCategoryWithHttpInfo($platform, $category_id, $lang, $pagination);
        return $response;
    }

    /**
     * Operation getSupplierByCategoryWithHttpInfo
     *
     * Get Supplier by Category
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     * @param  string $pagination Pagination for load more supplier list. Send supplierId (_id) last array (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ProductResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSupplierByCategoryWithHttpInfo($platform, $category_id, $lang = 'th', $pagination = null)
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByCategoryRequest($platform, $category_id, $lang, $pagination);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SystemError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSupplierByCategoryAsync
     *
     * Get Supplier by Category
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     * @param  string $pagination Pagination for load more supplier list. Send supplierId (_id) last array (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByCategoryAsync($platform, $category_id, $lang = 'th', $pagination = null)
    {
        return $this->getSupplierByCategoryAsyncWithHttpInfo($platform, $category_id, $lang, $pagination)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSupplierByCategoryAsyncWithHttpInfo
     *
     * Get Supplier by Category
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     * @param  string $pagination Pagination for load more supplier list. Send supplierId (_id) last array (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByCategoryAsyncWithHttpInfo($platform, $category_id, $lang = 'th', $pagination = null)
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByCategoryRequest($platform, $category_id, $lang, $pagination);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSupplierByCategory'
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     * @param  string $pagination Pagination for load more supplier list. Send supplierId (_id) last array (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSupplierByCategoryRequest($platform, $category_id, $lang = 'th', $pagination = null)
    {
        // verify the required parameter 'platform' is set
        if ($platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $platform when calling getSupplierByCategory'
            );
        }
        // verify the required parameter 'category_id' is set
        if ($category_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $category_id when calling getSupplierByCategory'
            );
        }

        $resourcePath = '/suppliers/{categoryId}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($pagination !== null) {
            $queryParams['pagination'] = ObjectSerializer::toQueryValue($pagination);
        }
        // header params
        if ($platform !== null) {
            $headerParams['platform'] = ObjectSerializer::toHeaderValue($platform);
        }
        // header params
        if ($lang !== null) {
            $headerParams['lang'] = ObjectSerializer::toHeaderValue($lang);
        }

        // path params
        if ($category_id !== null) {
            $resourcePath = str_replace(
                '{' . 'categoryId' . '}',
                ObjectSerializer::toPathValue($category_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSupplierByCategoryAll
     *
     * Get Supplier by Category all for show in map
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ProductResponse
     */
    public function getSupplierByCategoryAll($platform, $category_id, $lang = 'th')
    {
        list($response) = $this->getSupplierByCategoryAllWithHttpInfo($platform, $category_id, $lang);
        return $response;
    }

    /**
     * Operation getSupplierByCategoryAllWithHttpInfo
     *
     * Get Supplier by Category all for show in map
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ProductResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSupplierByCategoryAllWithHttpInfo($platform, $category_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByCategoryAllRequest($platform, $category_id, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SystemError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSupplierByCategoryAllAsync
     *
     * Get Supplier by Category all for show in map
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByCategoryAllAsync($platform, $category_id, $lang = 'th')
    {
        return $this->getSupplierByCategoryAllAsyncWithHttpInfo($platform, $category_id, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSupplierByCategoryAllAsyncWithHttpInfo
     *
     * Get Supplier by Category all for show in map
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByCategoryAllAsyncWithHttpInfo($platform, $category_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByCategoryAllRequest($platform, $category_id, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSupplierByCategoryAll'
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSupplierByCategoryAllRequest($platform, $category_id, $lang = 'th')
    {
        // verify the required parameter 'platform' is set
        if ($platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $platform when calling getSupplierByCategoryAll'
            );
        }
        // verify the required parameter 'category_id' is set
        if ($category_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $category_id when calling getSupplierByCategoryAll'
            );
        }

        $resourcePath = '/suppliers/{categoryId}/all';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($platform !== null) {
            $headerParams['platform'] = ObjectSerializer::toHeaderValue($platform);
        }
        // header params
        if ($lang !== null) {
            $headerParams['lang'] = ObjectSerializer::toHeaderValue($lang);
        }

        // path params
        if ($category_id !== null) {
            $resourcePath = str_replace(
                '{' . 'categoryId' . '}',
                ObjectSerializer::toPathValue($category_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSupplierById
     *
     * Get Supplier by id
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $supplier_id supplier id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ProductResponse
     */
    public function getSupplierById($platform, $category_id, $supplier_id, $lang = 'th')
    {
        list($response) = $this->getSupplierByIdWithHttpInfo($platform, $category_id, $supplier_id, $lang);
        return $response;
    }

    /**
     * Operation getSupplierByIdWithHttpInfo
     *
     * Get Supplier by id
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $supplier_id supplier id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ProductResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSupplierByIdWithHttpInfo($platform, $category_id, $supplier_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByIdRequest($platform, $category_id, $supplier_id, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SystemError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSupplierByIdAsync
     *
     * Get Supplier by id
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $supplier_id supplier id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByIdAsync($platform, $category_id, $supplier_id, $lang = 'th')
    {
        return $this->getSupplierByIdAsyncWithHttpInfo($platform, $category_id, $supplier_id, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSupplierByIdAsyncWithHttpInfo
     *
     * Get Supplier by id
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $supplier_id supplier id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByIdAsyncWithHttpInfo($platform, $category_id, $supplier_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByIdRequest($platform, $category_id, $supplier_id, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSupplierById'
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $supplier_id supplier id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSupplierByIdRequest($platform, $category_id, $supplier_id, $lang = 'th')
    {
        // verify the required parameter 'platform' is set
        if ($platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $platform when calling getSupplierById'
            );
        }
        // verify the required parameter 'category_id' is set
        if ($category_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $category_id when calling getSupplierById'
            );
        }
        // verify the required parameter 'supplier_id' is set
        if ($supplier_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $supplier_id when calling getSupplierById'
            );
        }

        $resourcePath = '/suppliers/{categoryId}/{supplierId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($platform !== null) {
            $headerParams['platform'] = ObjectSerializer::toHeaderValue($platform);
        }
        // header params
        if ($lang !== null) {
            $headerParams['lang'] = ObjectSerializer::toHeaderValue($lang);
        }

        // path params
        if ($category_id !== null) {
            $resourcePath = str_replace(
                '{' . 'categoryId' . '}',
                ObjectSerializer::toPathValue($category_id),
                $resourcePath
            );
        }
        // path params
        if ($supplier_id !== null) {
            $resourcePath = str_replace(
                '{' . 'supplierId' . '}',
                ObjectSerializer::toPathValue($supplier_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSupplierByShop
     *
     * Get Supplier by shop
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $shop_id shop id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ProductResponse
     */
    public function getSupplierByShop($platform, $category_id, $shop_id, $lang = 'th')
    {
        list($response) = $this->getSupplierByShopWithHttpInfo($platform, $category_id, $shop_id, $lang);
        return $response;
    }

    /**
     * Operation getSupplierByShopWithHttpInfo
     *
     * Get Supplier by shop
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $shop_id shop id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ProductResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSupplierByShopWithHttpInfo($platform, $category_id, $shop_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByShopRequest($platform, $category_id, $shop_id, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ProductResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SystemError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSupplierByShopAsync
     *
     * Get Supplier by shop
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $shop_id shop id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByShopAsync($platform, $category_id, $shop_id, $lang = 'th')
    {
        return $this->getSupplierByShopAsyncWithHttpInfo($platform, $category_id, $shop_id, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSupplierByShopAsyncWithHttpInfo
     *
     * Get Supplier by shop
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $shop_id shop id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierByShopAsyncWithHttpInfo($platform, $category_id, $shop_id, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\ProductResponse';
        $request = $this->getSupplierByShopRequest($platform, $category_id, $shop_id, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSupplierByShop'
     *
     * @param  string $platform platform (required)
     * @param  string $category_id supplier category id from supplier category object (required)
     * @param  string $shop_id shop id (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSupplierByShopRequest($platform, $category_id, $shop_id, $lang = 'th')
    {
        // verify the required parameter 'platform' is set
        if ($platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $platform when calling getSupplierByShop'
            );
        }
        // verify the required parameter 'category_id' is set
        if ($category_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $category_id when calling getSupplierByShop'
            );
        }
        // verify the required parameter 'shop_id' is set
        if ($shop_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shop_id when calling getSupplierByShop'
            );
        }

        $resourcePath = '/suppliers/shop/{shopId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($platform !== null) {
            $headerParams['platform'] = ObjectSerializer::toHeaderValue($platform);
        }
        // header params
        if ($lang !== null) {
            $headerParams['lang'] = ObjectSerializer::toHeaderValue($lang);
        }

        // path params
        if ($category_id !== null) {
            $resourcePath = str_replace(
                '{' . 'categoryId' . '}',
                ObjectSerializer::toPathValue($category_id),
                $resourcePath
            );
        }
        // path params
        if ($shop_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shopId' . '}',
                ObjectSerializer::toPathValue($shop_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSupplierCategory
     *
     * Get Supplier Category
     *
     * @param  string $platform platform (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\DesignerCategoryResponse
     */
    public function getSupplierCategory($platform, $lang = 'th')
    {
        list($response) = $this->getSupplierCategoryWithHttpInfo($platform, $lang);
        return $response;
    }

    /**
     * Operation getSupplierCategoryWithHttpInfo
     *
     * Get Supplier Category
     *
     * @param  string $platform platform (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\DesignerCategoryResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSupplierCategoryWithHttpInfo($platform, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\DesignerCategoryResponse';
        $request = $this->getSupplierCategoryRequest($platform, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\DesignerCategoryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SystemError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSupplierCategoryAsync
     *
     * Get Supplier Category
     *
     * @param  string $platform platform (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierCategoryAsync($platform, $lang = 'th')
    {
        return $this->getSupplierCategoryAsyncWithHttpInfo($platform, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSupplierCategoryAsyncWithHttpInfo
     *
     * Get Supplier Category
     *
     * @param  string $platform platform (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSupplierCategoryAsyncWithHttpInfo($platform, $lang = 'th')
    {
        $returnType = '\Swagger\Client\Model\DesignerCategoryResponse';
        $request = $this->getSupplierCategoryRequest($platform, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSupplierCategory'
     *
     * @param  string $platform platform (required)
     * @param  string $lang lang is th or en (optional, default to th)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSupplierCategoryRequest($platform, $lang = 'th')
    {
        // verify the required parameter 'platform' is set
        if ($platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $platform when calling getSupplierCategory'
            );
        }

        $resourcePath = '/suppliers/categories';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($platform !== null) {
            $headerParams['platform'] = ObjectSerializer::toHeaderValue($platform);
        }
        // header params
        if ($lang !== null) {
            $headerParams['lang'] = ObjectSerializer::toHeaderValue($lang);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
